name: Python CI

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run linting
        run: uv run ruff check .

      - name: Run type checking
        run: uv run mypy pactdesk/ main.py
